'''Python Webserver by sdmichelini
  
   Simple python script hosted on Google App Engine which Recieves Wordpress Webhook generated by IFTTT and forwards it to Spark Core

   Copyright (c) 2014 sdmichelini

	Permission is hereby granted, free of charge, to any person obtaining a copy of
	this software and associated documentation files (the "Software"), to deal in
	the Software without restriction, including without limitation the rights to
	use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
	the Software, and to permit persons to whom the Software is furnished to do so,
	subject to the following conditions:
	
	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
	FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
	COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
	IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
	CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

   TODO: Clean up code

'''

import webapp2
import logging
import json
import urllib
import urllib2

class MainPage(webapp2.RequestHandler):
	def post(self):
		data=json.loads(self.request.body)
		data['title']=data['title'].lower()
		#replace {ACCESS_TOKEN} and {DEVICE_ID}/{FUNCTION} with their proper values from your core
		postParameters = {'access_token' : {ACCESS_TOKEN}, 'command' :data['title']}
		url='https://api.spark.io/v1/devices/{DEVICE_ID}/{FUNCTION}'
		post_data_encoded = urllib.urlencode(postParameters)
		request_object = urllib2.Request(url, post_data_encoded)
		response = urllib2.urlopen(request_object)
		
		logging.info('Sent '+data['title']+' got response: ')

application = webapp2.WSGIApplication([('/', MainPage)],
	debug=True)
