'''Python Webserver by sdmichelini
  
   Simple python script hosted on Google App Engine which Recieves Wordpress Webhook generated by IFTTT and forwards it to Spark Core

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions are met:

   - Redistributions of source code must retain the above copyright notice,
     this list of conditions and the following disclaimer.
   - Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation
     and/or other materials provided with the distribution.

     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
     AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
     IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
     ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
     LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
     CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
     SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
     INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
     CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
     ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
     POSSIBILITY OF SUCH DAMAGE.

   TODO: Clean up code

'''

import webapp2
import logging
import json
import urllib
import urllib2

class MainPage(webapp2.RequestHandler):
	def post(self):
		data=json.loads(self.request.body)
		data['title']=data['title'].lower()
		#replace {ACCESS_TOKEN} and {DEVICE_ID}/{FUNCTION} with their proper values from your core
		postParameters = {'access_token' : {ACCESS_TOKEN}, 'command' :data['title']}
		url='https://api.spark.io/v1/devices/{DEVICE_ID}/{FUNCTION}'
		post_data_encoded = urllib.urlencode(postParameters)
		request_object = urllib2.Request(url, post_data_encoded)
		response = urllib2.urlopen(request_object)
		
		logging.info('Sent '+data['title']+' got response: ')

application = webapp2.WSGIApplication([('/', MainPage)],
	debug=True)